### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tomboy-64** [Ultimaker/Uranium#125]
Just for clarification, under which license is Uranium published?

**Comment by sedwards2009** [comment]
Uranium is released under the terms of the AGPLv3 or higher.

(Yes, we should have made that clearer in the README.)

**Comment by thopiekar** [comment]
@sedwards2009, so why closing that? We could leave it open until it's done..

**Comment by nallath** [comment]
Well, its almost in every single file.

**Comment by Ghostkeeper** [comment]
I have added a license to the repository and referenced to it from the readme.

**Comment by daid** [comment]
> Well, its almost in every single file.

And that's more important then the actual licence file. As that line says "this file is according to that license", the license file just says "this is a license", to make it extra clear. Without the line, it could be unclear what the license is, and you have to assume that the license file with the source should be applied on the source. And assumptions isn't that handy in legal cases.

**Comment by daid** [comment]
(Someone from Debian was quite clear on this when Cura started to gain traction years ago)
