### ISSUE TITLE
Slicing of tall objects does not start when 'One at a time' is set

### ISSUE THREAD

**Issue by michael-ring** [Ultimaker/Uranium#130]
On old cura I can slice my tall part (sorry, cannot share it, it is part of 3dpBurner) Name is ductV2
I get an error message that 'One at a time' is disabled because the part is too tall.

In Cura I only get 'Preparing to slice' when I have 'One at a time' active, when I switch to 'All at once' then slicing works.

Tested with Cura 2.1.0-20160318 on MacOSX 10.11.4

**Comment by fieldOfView** [comment]
The "preparing to slice" message should probably say something else in this case (something like "no objects are inside the buildvolume", but better), but other than that the behavior is as designed. 

New Cura tries not to second-guess the user and automatically change settings made by the user.

**Comment by Ghostkeeper** [comment]
Problem is actually that the preparation fails when it can't make the objects fit in the build volume, but the process is not actually aborted...

**Comment by michael-ring** [comment]
Would Cura display a similar error message like on old cura 

'One at a time' is disabled because the part is too tall

if the preparation process were properly aborted?

**Comment by Ghostkeeper** [comment]
Something like that can be produced then. A similar message could be produced when you place all objects next to the buildplate.
