### ISSUE TITLE
Cura dual extruder thin walls not generating gcode

### ISSUE THREAD

**Issue by jaredabrandt001** [Ultimaker/Uranium#134]
Application Version: Cura 15.04.6 or Cura engine running in Repetier Host
Platform: Windows 7 x64
Qt: don't know
PyQt: don't know
Display Driver: Quadro 2000 version 341.44
Printer: Large format Reprap Mendel

Steps to Reproduce:
Model size is approx 24"x24"x6" (large print), dual color.  Files are imported and extruders assigned to different models.  This machine has printed many large files, and I've used cura to print many single extruder prints.  I'd like to use Cura for dual extruder prints also and get away from Slic3r, but at the moment Cura does not process the gcode properly.  Slic3r does, but it takes 4-8 hours to slice.
Problem occurs in Cura 15.04.6 and Repetier host the same.
Cutting the model in half (reducing the file sizes) does not help.

Actual Results:
After slicing, gcode shows missing walls.  Missing walls tend to be in the same location.  Part prints with missing walls.  Wall thickness is set to 1.25mm with a 0.6mm extruder.  Perimeters are set to 0.6mm.  Mesh quality does not significantly impact the issue.
Note:  If all models are set to the same extruder (no dual extrusion) model gcode is generated correctly, so this issue is only with more than 1 extruder.

Expected results:
Should generate gcode where the model is solid.

Screenshots from Repetier Host:
![zoomout](https://cloud.githubusercontent.com/assets/19554372/15508861/2c5f1ac0-219f-11e6-99a5-7c1112ec58b7.jpg)
![zoomin](https://cloud.githubusercontent.com/assets/19554372/15508862/2c6ef76a-219f-11e6-827e-a17ec727e8c1.jpg)

Any help would be greatly appreciated!
Jared

**Comment by fieldOfView** [comment]
Please post issues with Cura 15.04.x here: https://github.com/daid/cura

Issues with Cura 2.1 and newer should be posted here: https://github.com/ultimaker/cura. Cura 2.1 was rewritten from scratch, and Uranium is one of the projects it is based on but is its own project on github (with its own unique issues, but generally issues should be posted against Cura).

**Comment by jaredabrandt001** [comment]
Ok, thanks Aldo.
I reposted it where suggested.
