### ISSUE TITLE
CMakeFiles\i18n-create-mo-tr.dir\build.make:56: recipe for target 'i18n-create-mo-tr' failed

### ISSUE THREAD

**Issue by chenjianyyzz** [Ultimaker/Uranium#182]
I try to build cura 2.3.1, I am using cura-build-2.3.1 under Win7 with mingw, and encounter the following error:

    CMakeFiles\i18n-create-mo-tr.dir\build.make:56: recipe for target 'i18n-create-mo-tr' failed
    make[5]: *** [i18n-create-mo-tr] Error 1
    CMakeFiles\Makefile2:791: recipe for target 'CMakeFiles/i18n-create-mo-tr.dir/all' failed
    make[4]: *** [CMakeFiles/i18n-create-mo-tr.dir/all] Error 2
    makefile:137: recipe for target 'all' failed
    make[3]: *** [all] Error 2
    CMakeFiles\Uranium.dir\build.make:110: recipe for target 'Uranium-prefix/src/Uranium-stamp/Uranium-build' failed
    make[2]: *** [Uranium-prefix/src/Uranium-stamp/Uranium-build] Error 2
    CMakeFiles\Makefile2:382: recipe for target 'CMakeFiles/Uranium.dir/all' failed
    make[1]: *** [CMakeFiles/Uranium.dir/all] Error 2
    makefile:148: recipe for target 'all' failed
    make: *** [all] Error 2

anybody know what's the problem and how to handle it?

Thanks 
James (chenjianyyzz@163.com)

**Comment by Ghostkeeper** [comment]
It looks like you were running `make i18n-create-mo`, which creates the machine-readable translation files. It also looks like you didn't copy enough of the log here. I think the real error is higher up in the build log.

You don't need to create the .mo files. You may try - it's not so hard, just simply runs `gettext` - but the files are pre-compiled already over in https://github.com/Ultimaker/cura-binary-data. If you don't compile the .mo files yourself, it should pluck them from cura-binary-data. That should circumvent this error.

**Comment by thopiekar** [comment]
@Ghostkeeper When building Cura the i18n-create-mo is called (it is part of target ALL).

@chenjianyyzz I think there must by more output when running e.g. `make -j4`, isn't it?

**Comment by Ghostkeeper** [comment]
> @Ghostkeeper When building Cura the i18n-create-mo is called (it is part of target ALL).

I thought we decided against that to prevent adding another build dependency. And those shell scripts won't run on Windows.

**Comment by thopiekar** [comment]
Hmm, if there is no Gettext there should be no i18n helper targets, see: https://github.com/Ultimaker/Uranium/blob/master/cmake/UraniumTranslationTools.cmake#L78

However, this is from [master].

**Comment by thopiekar** [comment]
Had these problems for a while, too, but now (after months) I did not see this problem anymore.
I assume it has been fixed now.
