### ISSUE TITLE
Write plugin developer guide / documentation

### ISSUE THREAD

**Issue by nallath** [Ultimaker/Uranium#20]
We need to improve the plugin developer guide / documentation and ensure this is proof read by (external?) developers.

**Comment by nickthetait** [comment]
I'd love to proof read and beta test this for you guys.

**Comment by Dim3nsioneer** [comment]
Just saw this... is there a draft of the docu yet?

**Comment by nallath** [comment]
Not as far as I'm aware. The only documentation that we have at this moment is in the code. We really need to work on this.

**Comment by nallath** [comment]
I've started work on this. Please check https://github.com/Ultimaker/Uranium/wiki/Plugin-Types

Its far from done, but at least it's a start. I will continue work on this, but i'm not sure how much time I will be able to put in this.

**Comment by awhiemstra** [comment]
Also, there is API documentation at http://software.ultimaker.com/uranium . This is generated from the sources and may be slightly outdated. I really should set up a cronjob to autogenerate it...
