### ISSUE TITLE
camera control bugs

### ISSUE THREAD

**Issue by Ando120** [Ultimaker/Uranium#213]
I made pull request to fix two camera control bugs and it was approved.
[https://github.com/Ultimaker/Uranium/pull/198](url)

But it s wasnt added to 2.4beta and not to 2.4beta2 too

Why its not in new cura version?

**Comment by Ghostkeeper** [comment]
Let's continue this discussion at your original pull request. I answered your question there: https://github.com/Ultimaker/Uranium/pull/198#issuecomment-274362772
