### ISSUE TITLE
Do not use dist-packages

### ISSUE THREAD

**Issue by ubitux** [Ultimaker/Uranium#222]
Python's `dist-packages` directory is debian specific and does not work on any other Linux distribution. The correct directory is `site-packages`.

Also, the correct directory for `site-packages` is not `python3` but `python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}`.

Unless these changes are made, no python import can work.

This issue is present in all other repositories.

**Comment by Ghostkeeper** [comment]
The issue pertains to this line of code: https://github.com/Ultimaker/Uranium/blob/43abd0f4fea1dd6f21e7f7002cad7f22b451f004/CMakeLists.txt#L58

However, we know that it also works on Arch. In fact, the guy who wrote that line of code works on Arch. In [the commit](https://github.com/Ultimaker/Uranium/commit/b1140ded3800651fb8ecdf28f0f009fc90c7d5a2) he mentions that it is meant to improve something for Debian though. @awhiemstra, do you know why dist-packages was used?

**Comment by ubitux** [comment]
It doesn't work on Arch, the `PKGBUILD` files patch the `CMakeLists.txt` with a `sed` to correct this. This only work on Debian-like systems.

**Comment by awhiemstra** [comment]
No indeed it does not, I just never really bothered with it since I use a custom pythonpath anyway when doing development.

Note that we already fixed this for Arcus: https://github.com/Ultimaker/libArcus/blob/master/CMakeLists.txt , we should do something similar here.

**Comment by Ghostkeeper** [comment]
Our product owner just closed this for being inactive for 3 months.
