### ISSUE TITLE
How did you generate the PyQt5 stubs?

### ISSUE THREAD

**Issue by fredrikaverpil** [Ultimaker/Uranium#253]
Perhaps a question for @sedwards2009: how did you go about generating these stubs?
https://github.com/Ultimaker/Uranium/tree/master/stubs/PyQt5

**Comment by sedwards2009** [comment]
They're from Riverbank, the maker of PyQt. I think there was a link on the mailing list and I grabbed them from there.

If you want more update to date stubs then you may have to ask Phil Thompson on the mailing list.

**Comment by fredrikaverpil** [comment]
@sedwards2009 ok, many thanks!

**Comment by awhiemstra** [comment]
They are generated as part of the PyQt build process actually. On my Arch machine they are actually included in the PyQt5 package.
