### ISSUE TITLE
Cura 2.6.2 Crashing

### ISSUE THREAD

**Issue by wmhoneycutt** [Ultimaker/Uranium#269]
Ironically, it runs fine on my Surface Pro 4, but I just bought a new computer to run Solidworks, and Cura 2.6.x won't run on my machine. The latest Cura 2.5 build, will run however. 

The very first time it starts up after install, it asks for me to select my printer, then freezes. After that, every time I try to start the program up, it just freezes.

I attached the log file for reference. 
[cura - Copy.txt](https://github.com/Ultimaker/Uranium/files/1168343/cura.-.Copy.txt)

**Comment by Ghostkeeper** [comment]
The log shows nothing special. But it indeed seems to crash just when it's creating the main window. Perhaps update your video drivers?

Since you closed the issue, did you happen to find a solution to your problem already?

**Comment by wmhoneycutt** [comment]
Hey Ghostkeeper,
I greatly appreciate your following up with me! I think it was a mix of issues. I friggin’ loathe Windows (I’m a Mac guy, like before Steve Jobs died Mac Guy, not so much now), and I think it was a mix of issues.

One – After the torturing 6 hour (not an exaggeration) setup process of downloading updates, installing updates, and initializing updates (whatever that means), I did double check the graphics card drivers and noticed that they were not up to date.

Two – I have my laptop connected to a HD monitor, and I began to notice that when I wasn’t connected to the external monitor, SolidWorks 2017 would run perfectly fine. However, when I was connected, it would always crash. Same with Cura, and same with the trial version of Simply3D that I downloaded, just for testing purposes. I then realized, that even though the machine has great performance in terms of speed and processing, the graphics card on it could not handle the complex rendering of 3D objects on an external monitor.

                >Note: I have the monitor set up as an extension of my current desktop, I have not tested it where the computer displays only on the monitor since I discovered the issue.

I realize this was probably a lot more detail than you needed. However, I have been in the Tech Support Business myself and I understand that there is no such thing as too much information when it comes to how a consumer solved a technical problem.

If you need anymore information, don’t hesitate to contact me.


-William Honeycutt

“Wonder is the desire for knowledge.” -Thomas Aquinas
