### ISSUE TITLE
AddSceneNodeOperation not fully loading SceneNode issue

### ISSUE THREAD

**Issue by hamzaalomari** [Ultimaker/Uranium#270]
When I add a new _SceneNode_ to the scene, it doesn't load fully, it is greyed out as if it still needs something more than just simply adding it the scene.
In Cura 2.4 _AddSceneNodeOperation_ worked perfectly, but in Cura 2.6.2 it doesn't work.
![capture](https://user-images.githubusercontent.com/13904513/28877395-e734b6b4-77a4-11e7-94a4-8aa8cb3b4ad8.PNG)

**Comment by nallath** [comment]
Did you add the slicable scenenode decorator?

**Comment by hamzaalomari** [comment]
Adding the sliceable scenenode decorator solved the problem.
