### ISSUE TITLE
PPA: Failing testing suite on Ubuntu Xenial

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Uranium#271]
Other Ubuntu releases are not affected.

https://launchpad.net/~thopiekar/+archive/ubuntu/cura-master/+build/13211725/+files/buildlog_ubuntu-xenial-amd64.uranium_1%3A2.6.99-master~201708071148~rev1938~pkg159~ubuntu16.04.1_BUILDING.txt.gz

**Comment by awhiemstra** [comment]
Those failing tests are those that have been explicitly marked as "skip" in the test files. It seems something has decided to run them anyway.

**Comment by thopiekar** [comment]
Maybe the module in Xenial is too old to understand this setting.. Must be something simple :wink:
