### ISSUE TITLE
Translate camera

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Uranium#28]
Shift + right click + drag = translate camera, just like the old cura.

**Comment by nickthetait** [comment]
I'd just like to point out that I've been using Cura for almost three years, never knew it was possible to translate/pan the camera. :open_mouth:

**Comment by nallath** [comment]
Now you know :)

**Comment by BagelOrb** [comment]
Still not working. Nothing happens when dragging while holding middle mouse button.

OS: Ubuntu 15.04

**Comment by nallath** [comment]
Works on my machine, also Ubuntu 15.04.

**Comment by BagelOrb** [comment]
Application version: dev

Qt version: 4.8.6 

> apt-show-versions python3-pyqt5
python3-pyqt5:amd64/vivid 5.4.1+dfsg-2 uptodate

> sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: Haswell-ULT Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0

**Comment by BagelOrb** [comment]
Working on Cura:master + Uranium:master
