### ISSUE TITLE
How to install Uranium in fedora 26

### ISSUE THREAD

**Issue by vivekanand1101** [Ultimaker/Uranium#282]
I want to checkout this framework on my system. How do i install it? via ```dnf```?

**Comment by nallath** [comment]
I'd recommend using git clone.

**Comment by vivekanand1101** [comment]
Closing this one as i am satisfied :)

Note for any one else who stumbles on this:
You will have to include Uranium in PYTHONPATH for using Cura:  export PYTHONPATH=$PYTHONPATH:/home/username/Uranium

(given that Uranium is cloned in /home/username)
