### ISSUE TITLE
3.0.0: Failing test suite

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Uranium#286]
Is that a known problem? Can I safely skip these tests?

https://launchpadlibrarian.net/338993170/buildlog_ubuntu-artful-amd64.uranium_1%3A2.7.0~201709280927~rev1971~pkg165~ubuntu17.10.1_BUILDING.txt.gz

- https://github.com/thopiekar/Cura-packaging/issues/28

**Comment by thopiekar** [comment]
🙄

**Comment by nallath** [comment]
The tests aren't failing on my local machine. Well, they were, but not on those items. 

As far as the logs show, there is an permission issue that is causing the tests to fail (as it tries to make folders and fails to do so)

**Comment by thopiekar** [comment]
Alright, I'm ignoring these problems then.

**Comment by thopiekar** [comment]
Could we fix this problem on master then? Afaik, these issues are there, too.

**Comment by nallath** [comment]
They also work for master when I'm using them locally.

**Comment by thopiekar** [comment]
Hmm, getting the same now when building Cura:
https://launchpadlibrarian.net/339584889/buildlog_ubuntu-zesty-amd64.cura_1%3A2.7.0~201710031051~rev2203~pkg166~ubuntu17.04.1_BUILDING.txt.gz

**Comment by thopiekar** [comment]
Looks like a systematic mistake by me or someone else..
