### ISSUE TITLE
ImportError: cannot import name 'TYPE_CHECKING'

### ISSUE THREAD

**Issue by midyukov-anton** [Ultimaker/Uranium#296]
Hi!
I'm trying to build a package Uranium 3.0.3 for ALT Linux. The test does not pass:

> /usr/bin/python3 -m pytest -v -k 'not getMimeTypeForFile'
> Traceback (most recent call last):
>   File "/usr/lib/python3/site-packages/_pytest/config.py", line 342, in _getconftestmodules
>     return self._path2confmods[path]
> KeyError: local('/usr/src/RPM/BUILD/Uranium-3.0.3/tests')
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/lib/python3/site-packages/_pytest/config.py", line 373, in _importconftest
>     return self._conftestpath2mod[conftestpath]
> KeyError: local('/usr/src/RPM/BUILD/Uranium-3.0.3/tests/conftest.py')
> 
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/usr/lib/python3/site-packages/_pytest/config.py", line 379, in _importconftest
>     mod = conftestpath.pyimport()
>   File "/usr/lib/python3/site-packages/py/_path/local.py", line 662, in pyimport
>     __import__(modname)
>   File "/usr/lib/python3/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
>     py.builtin.exec_(co, mod.__dict__)
>   File "/usr/src/RPM/BUILD/Uranium-3.0.3/tests/conftest.py", line 6, in <module>
>     from UM.Qt.QtApplication import QtApplication
>   File "/usr/src/RPM/BUILD/Uranium-3.0.3/UM/Qt/QtApplication.py", line 15, in <module>
>     from UM.FileHandler.ReadFileJob import ReadFileJob
>   File "/usr/src/RPM/BUILD/Uranium-3.0.3/UM/FileHandler/ReadFileJob.py", line 4, in <module>
>     from UM.Job import Job
>   File "/usr/src/RPM/BUILD/Uranium-3.0.3/UM/Job.py", line 8, in <module>
>     from UM.JobQueue import JobQueue
>   File "/usr/src/RPM/BUILD/Uranium-3.0.3/UM/JobQueue.py", line 10, in <module>
>     from typing import TYPE_CHECKING, List, Callable, Any
> ImportError: cannot import name 'TYPE_CHECKING'
> ERROR: could not load /usr/src/RPM/BUILD/Uranium-3.0.3/tests/conftest.py

> python3 --version
> Python 3.5.1

python 3.5 is supported? Or do I need python3.6?

**Comment by ChrisTerBeke** [comment]
From https://github.com/python/mypy/blob/master/docs/source/common_issues.rst#import-cycles:

```
Python 3.5.1 doesn't have typing.TYPE_CHECKING.
```

So upgrading python should do the trick.

**Comment by Ghostkeeper** [comment]
Until last Wednesday I'd been using Python 3.5.2 to run Cura and the unit tests, as it came with Ubuntu 17.04. Always worked for me. Only last Wednesday when Ubuntu 17.10 was released did I upgrade to 3.6.

Also our build system currently uses 3.5.2: https://github.com/Ultimaker/cura-build-environment/blob/a9ae4b2efe9f89772f1c71b7245606857f62870c/projects/python.cmake#L36
