### ISSUE TITLE
Redundant event emit

### ISSUE THREAD

**Issue by daid** [Ultimaker/Uranium#297]
https://github.com/Ultimaker/Uranium/blob/969c802eda8e27e5b798001a41a3cd320ede9289/UM/Qt/ListModel.py#L69
The items changed signal is emitted twice in the appendItem function, as it's just using the insert function which already emits the signal.
(No idea how often it is used, was just browsing the code when noticed this)

**Comment by ChrisTerBeke** [comment]
Yeah, there's a *few* more occurrences of that in Cura... :P

**Comment by daid** [comment]
Well with performance on the radar for upcoming updates, I figured I report it ;-)

**Comment by Ghostkeeper** [comment]
I've removed it since it's so obviously wrong. I don't notice much performance increase but it should be slightly better in the "Creating interface" stage of start-up since that's when these list models are usually filled up.
