### ISSUE TITLE
Rotate object snapping to wrong start point

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Uranium#31]
Half of the time when I rotate an object, the first angle it snaps to is something like 1 degree instead of 0 degrees.

![pluggcura_wrong_rotation](https://cloud.githubusercontent.com/assets/8895761/7412388/9fbdceac-ef42-11e4-9637-ca1a3be92591.png)

**Comment by daid** [comment]
Not sure if this is related or a new bug, so reporting it here. When I try to rotate an object around 180 deg (upside down) I'm not getting it flat on it's original top.

**Comment by awhiemstra** [comment]
Fixed by 8e4961347dcb13ff6b98613894854e3c177f7bee
