### ISSUE TITLE
Doc links 404 error

### ISSUE THREAD

**Issue by PicoPi** [Ultimaker/Uranium#341]
Please fix the broken link to the docs on readme.md main page.
It gives 404 error

**Comment by ianpaschal** [comment]
It never actually existed, so I have removed the broken link.

Instead, please check the docs folder.

**Comment by PicoPi** [comment]
that is also broken!
https://github.com/Ultimaker/Uranium/blob/master/docs/docs/overview.md

**Comment by PicoPi** [comment]
https://github.com/Ultimaker/Uranium/blob/master/docs/mainpage.md

**Comment by diegopradogesto** [comment]
I've fixed those links in db7833d86ce36f6033549ffc516acac55ac418b3
