### ISSUE TITLE
Uranium only tries to find its plugins into $prefix/lib/

### ISSUE THREAD

**Issue by krop** [Ultimaker/Uranium#347]
Title almost tells everything. When starting Cura, it crashes because:
[MainThread] cura.CrashHandler.__init__ [68]: UM.PluginError.PluginNotFoundError: Could not find plugin ConsoleLogger

UM/Application.py only looks in lib/
self._plugin_registry.addPluginLocation(os.path.join(Application.getInstallPrefix(), "lib", "uranium"))

The plugins can be installed anywhere (lib64 in my case)

**Comment by thopiekar** [comment]
Yep, true thing. Not all distributions are using lib like Debian and Ubuntu. But in my opinion this issue is easy to fix. 🙂

**Comment by krop** [comment]
I fixed it at packaging level. The report is just there to remind me I need to make a correct patch :)
I'm now trying to understand why python segfaults when starting Cura.

**Comment by thopiekar** [comment]
You have these segmentation faults with PyQt5 5.10? It needs a patch. Look into the Ubuntu bionic package.

If you find time, then fix it by generating a python file via CMake. CMake is the first instance and knows of the lib path, which shall be used for the installation. I think this is the cleanest solution to solve this.
If you don't know show to generate this file, take a look at CMakeLists.txt and Cura/CuraVersion.py.in in the Cura project. The you can find the name of the CMake variable pretty quick.

If you are going for this solution, then you'll get my thumbs up 😉👍

**Comment by krop** [comment]
That was my plan, I have 2 buildsystem PR pending and another one to submit after that.

**Comment by thopiekar** [comment]
Nice! Accidentally found something useless in CMakeLists.txt this morning. But that was Debian/Ubuntu specific 😉

**Comment by krop** [comment]
ping ?
