### ISSUE TITLE
Autoplacement relocates wrong objects

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Uranium#35]
(And also causes minor vizualization bug which helps me in showing that the wrong object has been moved)
![pluggcura_wrong_autoplacement](https://cloud.githubusercontent.com/assets/8895761/7412604/bdaf5ac8-ef44-11e4-8ba3-e5f1a43d0ca7.png)
I selected the robot, dragged it over the wolf and then the selected robot got relocated instead of the wolf.

**Comment by awhiemstra** [comment]
This should be fixed in recent versions.
