### ISSUE TITLE
Uranium-3.4.1: 18 test failed

### ISSUE THREAD

**Issue by midyukov-anton** [Ultimaker/Uranium#367]
Distributiv ALT Linux
python 3.6.5
numpy 1.13.3
scipy 1.0.0
PyQt5 5.9.2

=================================== FAILURES ===================================
____________________________ test_addContainerType _____________________________

container_registry = <UM.Settings.ContainerRegistry.ContainerRegistry object at 0x7f0460586470>
plugin_registry = <UM.PluginRegistry.PluginRegistry object at 0x7f0470b7bc18>

    def test_addContainerType(container_registry, plugin_registry):
        old_container_type_count = len(container_registry._ContainerRegistry__container_types)
        plugin_registry.addPluginLocation(os.path.dirname(os.path.abspath(__file__))) # Load plug-ins relative to this file.
        plugin_registry.loadPlugins()
        # The __init__ script now adds itself to the container registry.
>       assert len(container_registry._ContainerRegistry__container_types) == old_container_type_count + 1
E       AssertionError: assert 3 == (3 + 1)
E        +  where 3 = len({'definition': <class 'UM.Settings.DefinitionContainer.DefinitionContainer'>, 'instance': <class 'UM.Settings.InstanceContainer.InstanceContainer'>, 'stack': <class 'UM.Settings.ContainerStack.ContainerStack'>})
E        +    where {'definition': <class 'UM.Settings.DefinitionContainer.DefinitionContainer'>, 'instance': <class 'UM.Settings.InstanceContainer.InstanceContainer'>, 'stack': <class 'UM.Settings.ContainerStack.ContainerStack'>} = <UM.Settings.ContainerRegistry.ContainerRegistry object at 0x7f0460586470>._ContainerRegistry__container_types

tests/Settings/TestContainerRegistry.py:169: AssertionError
---------------------------- Captured stdout setup -----------------------------
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
---------------------------- Captured stderr setup -----------------------------
QSocketNotifier: Can only be used with threads started with QThread
----------------------------- Captured stdout call -----------------------------
[MainThread] UM.Logger.logException [81]: Exception: Error loading plugin ContainerTestPlugin:
[MainThread] UM.Logger.logException [85]: Traceback (most recent call last):
[MainThread] UM.Logger.logException [85]:   File "/usr/src/RPM/BUILD/Uranium-3.4.1/UM/PluginRegistry.py", line 416, in loadPlugin
[MainThread] UM.Logger.logException [85]:     to_register = plugin.register(self._application) #type: ignore #We catch AttributeError on this in case register() doesn't exist.
[MainThread] UM.Logger.logException [85]:   File "/usr/src/RPM/BUILD/Uranium-3.4.1/tests/Settings/ContainerTestPlugin/__init__.py", line 15, in register
[MainThread] UM.Logger.logException [85]:     return { "settings_container": ContainerTestPlugin() }
[MainThread] UM.Logger.logException [85]:   File "/usr/src/RPM/BUILD/Uranium-3.4.1/UM/Decorators.py", line 90, in new_new
[MainThread] UM.Logger.logException [85]:     raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
[MainThread] UM.Logger.logException [85]: NotImplementedError: Class <class 'ContainerTestPlugin.ContainerTestPlugin.ContainerTestPlugin'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty
_______________________________ test_uniqueName ________________________________

container_registry = <UM.Settings.ContainerRegistry.ContainerRegistry object at 0x7f046022ac50>

    def test_uniqueName(container_registry):
        assert container_registry.uniqueName("test") == "test" #No collisions.
    
>       mock_container = MockContainer(metadata = {"id": "test"})

tests/Settings/TestContainerRegistry.py:355: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerRegistry.MockContainer'>, args = ()
kwargs = {'metadata': {'id': 'test'}}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerRegistry.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
---------------------------- Captured stdout setup -----------------------------
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
---------------------------- Captured stderr setup -----------------------------
QSocketNotifier: Can only be used with threads started with QThread
______________________________ test_addContainer _______________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460312ee8>

    def test_addContainer(container_stack):
        assert container_stack.getContainers() == [] # First nothing.
>       container = MockContainer()

tests/Settings/TestContainerStack.py:141: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data0] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f046055ae58>
data = {'containers': [{}, {}], 'description': 'Search empty', 'filter': {}, 'result': {}}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data1] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f04602120d8>
data = {'containers': [{'foo': 'baz'}], 'description': 'Not found', 'filter': {'foo': 'bar'}, 'result': None}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data2] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212168>
data = {'containers': [{'loo': 'bar'}], 'description': 'Key not found', 'filter': {'foo': 'bar'}, 'result': None}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data3] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212dc8>
data = {'containers': [{'id': 'a', 'mixed': 10, 'number': 1, 'string': 'foo'}, {'id': 'b', 'mixed': 'bar', 'number': 2, 'stri...filter': {'mixed': 10, 'number': 1, 'string': 'foo'}, 'result': {'id': 'a', 'mixed': 10, 'number': 1, 'string': 'foo'}}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data4] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212d38>
data = {'containers': [{'id': 'a', 'string': 'foo'}, {'id': 'b', 'number': 1}, {'id': 'c', 'number': 2}], 'description': 'Wildcard Number', 'filter': {'number': '*'}, 'result': {'id': 'c', 'number': 2}}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_findContainer[data5] ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212ca8>
data = {'containers': [{'id': 'a', 'number': 1}, {'id': 'b', 'string': 'foo'}, {'id': 'c', 'string': 'boo'}], 'description': 'Wildcard String', 'filter': {'string': '*'}, 'result': {'id': 'c', 'string': 'boo'}}

    @pytest.mark.parametrize("data", test_findContainer_data)
    def test_findContainer(container_stack, data):
        for container in data["containers"]: # Add all containers.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:382: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
______________________________ test_getContainer _______________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212048>

    def test_getContainer(container_stack):
        with pytest.raises(IndexError):
            container_stack.getContainer(0)
    
        # Fill with data.
>       container1 = MockContainer()

tests/Settings/TestContainerStack.py:403: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
_____________________________ test_getValue[data1] _____________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212288>
data = {'containers': [{'boo': 'bar'}], 'description': 'Nonexistent key', 'key': 'foo', 'result': None}

    @pytest.mark.parametrize("data", test_getValue_data)
    def test_getValue(container_stack, data):
        # Fill the container stack with the containers.
        for container in reversed(data["containers"]): # Reverse order to make sure the last-added item is the top of the list.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:482: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
_____________________________ test_getValue[data2] _____________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212318>
data = {'containers': [{'foo': 'bar'}, {'foo': 'baz'}], 'description': 'First hit', 'key': 'foo', 'result': 'bar'}

    @pytest.mark.parametrize("data", test_getValue_data)
    def test_getValue(container_stack, data):
        # Fill the container stack with the containers.
        for container in reversed(data["containers"]): # Reverse order to make sure the last-added item is the top of the list.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:482: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
_____________________________ test_getValue[data3] _____________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f04602123a8>
data = {'containers': [{'boo': 'baz'}, {'zoo': 'bam'}, {'foo': 'bar'}], 'description': 'Third hit', 'key': 'foo', 'result': 'bar'}

    @pytest.mark.parametrize("data", test_getValue_data)
    def test_getValue(container_stack, data):
        # Fill the container stack with the containers.
        for container in reversed(data["containers"]): # Reverse order to make sure the last-added item is the top of the list.
>           mockup = MockContainer()

tests/Settings/TestContainerStack.py:482: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
_____________________________ test_removeContainer _____________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f04602120d8>

    def test_removeContainer(container_stack):
        # First test the empty case.
        with pytest.raises(IndexError):
            container_stack.removeContainer(0)
    
        # Now add data.
>       container0 = MockContainer()

tests/Settings/TestContainerStack.py:499: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
____________________________ test_replaceContainer _____________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460212d38>

    def test_replaceContainer(container_stack):
        # First test the empty case.
        with pytest.raises(IndexError):
>           container_stack.replaceContainer(0, MockContainer())

tests/Settings/TestContainerStack.py:526: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
______________________________ test_setNextStack _______________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460329c18>

    def test_setNextStack(container_stack):
>       container = MockContainer()

tests/Settings/TestContainerStack.py:691: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = (), kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
__________________________ test_backwardCompatibility __________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f04603295e8>
container_registry = <UM.Settings.ContainerRegistry.ContainerRegistry object at 0x7f0464a264e0>

    def test_backwardCompatibility(container_stack, container_registry):
>       container_a = MockContainer("a")

tests/Settings/TestContainerStack.py:703: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = ('a',)
kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
---------------------------- Captured stdout setup -----------------------------
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
---------------------------- Captured stderr setup -----------------------------
QSocketNotifier: Can only be used with threads started with QThread
___________________________ test_idSpecialCharacters ___________________________

container_stack = <UM.Settings.ContainerStack.ContainerStack object at 0x7f0460329c18>
container_registry = <UM.Settings.ContainerRegistry.ContainerRegistry object at 0x7f0460336b00>

    def test_idSpecialCharacters(container_stack, container_registry):
>       container_ab = MockContainer("a,b") # Comma used to break deserialize

tests/Settings/TestContainerStack.py:720: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

subclass = <class 'TestContainerStack.MockContainer'>, args = ('a,b',)
kwargs = {}
method = ('setProperty', <function ContainerInterface.setProperty at 0x7f046470d488>)
sub_method = <function ContainerInterface.setProperty at 0x7f046470d488>

    def new_new(subclass, *args, **kwargs):
        if cls != subclass:
            for method in filter(lambda i: inspect.isfunction(i[1]) and not i[1].__name__.startswith("__") and not i[0].startswith("__"), inspect.getmembers(cls)):
                sub_method = getattr(subclass, method[0])
                if sub_method == method[1]:
>                   raise NotImplementedError("Class {0} does not implement the complete interface of {1}: Missing method {2}".format(subclass, cls, method[0]))
E                   NotImplementedError: Class <class 'TestContainerStack.MockContainer'> does not implement the complete interface of <class 'UM.Settings.Interfaces.ContainerInterface'>: Missing method setProperty

UM/Decorators.py:90: NotImplementedError
---------------------------- Captured stdout setup -----------------------------
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
[MainThread] UM.Settings.InstanceContainer.getVersionFromSerialized [479]: Could not determine configuration type.
---------------------------- Captured stderr setup -----------------------------
QSocketNotifier: Can only be used with threads started with QThread
=============================== warnings summary ===============================
tests/benchmarks/conftest.py
  Skipping benchmarks because pytest-benchmark plugin was not found.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
============================== 1 tests deselected ==============================
= 18 failed, 246 passed, 26 skipped, 1 deselected, 1 warnings in 8.79 seconds ==
error: Bad exit status from /usr/src/tmp/rpm-tmp.32013 (%check)

**Comment by diegopradogesto** [comment]
We were fixing the tests some weeks ago (in `master` branch BTW) and they seem to be fixed now in our build environment.
![image](https://user-images.githubusercontent.com/15830521/43121857-6fd083a8-8f1f-11e8-9ee8-847486fb5212.png)
