### ISSUE TITLE
deb/rpm Packages

### ISSUE THREAD

**Issue by awhiemstra** [Ultimaker/Uranium#42]
For the release, I would like to have deb and rpm packages that people can use. These can be built with CPack and do not need to be perfect but would at least provide a starting point.

**Comment by nickthetait** [comment]
:raised_hand: I think this one got closed accidentally

**Comment by nallath** [comment]
Good catch, It's problem with tracking issues over 2 projects in github.

**Comment by nickthetait** [comment]
:smile:

**Comment by nickthetait** [comment]
Just tried to use the brand new Linux packages (15.06.01) but I get several dependency problems while trying to install. Here's the complaints given on Debian Jessie 64 bit:

sudo dpkg -i Cura-15.06.01-Linux.deb 
(Reading database ... 276937 files and directories currently installed.)
Preparing to unpack Cura-15.06.01-Linux.deb ...
Unpacking cura (15.06.01) over (15.02.1-1.03-c9801) ...
dpkg: dependency problems prevent configuration of cura:
 cura depends on python3-pyqt5 (>= 5.4.0); however:
  Version of python3-pyqt5 on system is 5.3.2+dfsg-3.
 cura depends on python3-pyqt5.qtopengl (>= 5.4.0); however:
  Version of python3-pyqt5.qtopengl on system is 5.3.2+dfsg-3.
 cura depends on python3-pyqt5.qtquick (>= 5.4.0); however:
  Version of python3-pyqt5.qtquick on system is 5.3.2+dfsg-3.
 cura depends on python3-pyqt5.qtsvg (>= 5.4.0); however:
  Version of python3-pyqt5.qtsvg on system is 5.3.2+dfsg-3.
 cura depends on python3-serial (>= 2.6); however:
  Package python3-serial is not installed.
 cura depends on qml-module-qtquick2 (>= 5.4.0); however:
  Version of qml-module-qtquick2:amd64 on system is 5.3.2-4.
 cura depends on qml-module-qtquick-window2 (>= 5.4.0); however:
  Version of qml-module-qtquick-window2:amd64 on system is 5.3.2-4.
 cura depends on qml-module-qtquick-layouts (>= 5.4.0); however:
  Version of qml-module-qtquick-layouts:amd64 on system is 5.3.2-2.
 cura depends on qml-mo
dpkg: error processing package cura (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Errors were encountered while processing:
 cura

**Comment by awhiemstra** [comment]
Unfortunately we require PyQt 5.4 due to known issues with prior versions of PyQt. These packages are only available in Debian Testing or unstable. I do not know if they will be backported to Jessie. In the meantime, I have some plans to create a debian package that includes Qt and PyQt, but those will take some time to be finished.

**Comment by nickthetait** [comment]
OK, thanks for the explanation. You're doing lots of awesome work!

**Comment by thopiekar** [comment]
These are the packaging files I use for my Ubuntu PPA.
* https://code.launchpad.net/~thopiekar/+junk/Cura-packaging
* https://code.launchpad.net/~thopiekar/+junk/Uranium-packaging
* https://code.launchpad.net/~thopiekar/+junk/libArcus-packaging
* https://code.launchpad.net/~thopiekar/+junk/CuraEngine-packaging
