### ISSUE TITLE
Why Uranium?

### ISSUE THREAD

**Issue by CharlesFr** [Ultimaker/Uranium#438]
> Uranium is a Python framework for building 3D printing related applications.

Could someone explain why Uranium is particularly well suited for 3DP applications?

Also, is there a "Hello world" example I can review?

**Comment by nallath** [comment]
Well, it's a bit of a long story. But the notion of Uranium is that it's a framework to build CAM applications. Cura is the most (and only publicly available) example of this. But it's also being used to develop a scanner application and i've also seen some prototypes that actually use it to build CNC routing software. 

Uranium in the basics provides a framework to handle settings, a link to a backend that does a bunch of computations and a whole slew of default plugins (scene manipulation, file loading / storing, etc).

**Comment by CharlesFr** [comment]
In the context of Cura, can you clarify what is referred to as the backend?

Is the OpenGl implement of pyQt being used to render the 3D stuff?

**Comment by fieldOfView** [comment]
In the case of Cura, the "backend" is CuraEngine; the backend does the calculation intensive stuff ("slicing" for Cura), which you would not want to implement in the front-end.
