### ISSUE TITLE
Errors when scanning for removable devices

### ISSUE THREAD

**Issue by awhiemstra** [Ultimaker/Uranium#46]
Platform: Windows 7
Qt: 5.4.1
PyQt: 5.4.1

Steps to Reproduce:
* Have a machine with certain configurations of Card readers
* Start the application

Actual Results:
* Every time a scan is done for removable drives it will try to access a drive with no actual media inserted. This will cause Windows to popup an error dialog.

Expected results:
* Removable device scanning is silent with no errors.

Additional Information:
Screenshot: 
![errormessage](https://cloud.githubusercontent.com/assets/9590386/7652049/f3a758b4-fb07-11e4-8837-f0129ff510d4.jpg)

**Comment by daid** [comment]
https://msdn.microsoft.com/en-us/library/ms680621(VS.85).aspx

Might help for this case.
