### ISSUE TITLE
Just install this version of UM and is install in python3.5 instead of python3.7

### ISSUE THREAD

**Issue by ibyte8bits** [Ultimaker/Uranium#489]
Compiling from the download of this repository and install to /usr/local.  It placed the UM in the /usr/local/lib/python3.5/site-packages directory.  The Cura, CuraEngine, and the libArcus all install in the /usr/local/python3.7/site-packages directory.  Just a slight mistake that took a while to figure out.  I moved the UM directory to the /usr/local/lib/python3.7/site-packages directory and Cura finally started.

**Comment by thopiekar** [comment]
You probably need to set the version of Python which CMake shall use to build Uranium.
I'm building Uranium in a "Personal Package Archive" just fine.

You can take the files from here:
https://github.com/thopiekar/Cura-packaging/tree/master/Uranium
Drop them into "debian" in Uranium's source directory and build it with "dpkg-build-package -rfakeroot". This tool is included in dpkg-dev I think. All dependencies are listed here:
https://github.com/thopiekar/Cura-packaging/blob/master/Uranium/control#L5

Regards
- Thomas

**Comment by Ghostkeeper** [comment]
Uranium is asking for 3.5.0 as minimum. Maybe it's not finding your 3.7 version properly? Or maybe there is a bug in CMake's FindPythonInterp script? It's been superseded in CMake 3.12 so in the future we'll be switching to a different built-in finder script.
