### ISSUE TITLE
Dark themes/unreadable text

### ISSUE THREAD

**Issue by ad1217** [Ultimaker/Uranium#49]
I use a dark theme in Qt, and it sets a light font color. The backgrounds of tool-tips seem to be a static color, so text is completely unreadable. Text in setting boxes also become almost unreadable. It would be good to have those depend upon the theme. Though ideally, the whole UI should be somehow themeable.

**Comment by ad1217** [comment]
Upon closer investigation (i.e. actually looking at the structure of Uranium/Cura) this is a Cura theme issue. And Cura does have theme support, so it turned out to be not all that hard to firx.

**Comment by Ghostkeeper** [comment]
May I ask what you did to fix it? If it's an issue with the default theme on your OS then we could have a look into it.

**Comment by ad1217** [comment]
I just changed the color of the tooltip (in theme.json) to a better color for my text (black). The only thing I would recommend is setting the color of the tooltip's text to black or something, rather than relying on the user's theme.
