### ISSUE TITLE
View flipping when viewing object from top or bottom

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Uranium#50]
When you try to view an object exactly from above, by right clicking and dragging down or up and the camera is aligned with the Z axis the view starts flipping upside down every frame you move the mouse, until you drag the view to a normal position again.
![curaflippinview](https://cloud.githubusercontent.com/assets/8895761/7938268/f53a9d12-0944-11e5-8988-1f8551c8f3d1.png)

I suggest a quick hack which limits the camera angle to 89 degrees instead of 90.

**Comment by BagelOrb** [comment]
This issue can now be closed, right?

**Comment by BagelOrb** [comment]
This bug still occurs on my machine. 
The view always flips over the Y direction of the buildplate, not horizontally over the screen.

Application version: dev

Qt version: 4.8.6 

> apt-show-versions python3-pyqt5
python3-pyqt5:amd64/vivid 5.4.1+dfsg-2 uptodate

> sudo lshw -c video
  *-display               
       description: VGA compatible controller
       product: Haswell-ULT Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0

**Comment by nallath** [comment]
Did you check this with the right branch?

**Comment by BagelOrb** [comment]
No I did not check it right. Pulled Cura without pulling Uranium :S 
Sorry!

It is working on my machine now. :)
