### ISSUE TITLE
Can't see results of Continuous Integration Tests

### ISSUE THREAD

**Issue by digitalfrost** [Ultimaker/Uranium#512]
Steps to reproduce:
- Go to pull request #510 
- _Under All Checks have failed_
             _continuous-integration/jenkins/pr-merge — This commit has test failures_
             **Click on** _Details_

Results in:
This site can’t be reached hal9000.ultimaker.com took too long to respond... ERR_CONNECTION_TIMED_OUT

Expected Result:
Seeing the results of the tests like for example
https://travis-ci.org/engineyard/core-client-rb/builds/379803159?utm_source=github_status&utm_medium=notification

**Comment by digitalfrost** [comment]
```
$ ping hal9000.ultimaker.com

Pinging hal9000.ultimaker.com [159.100.101.100] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 159.100.101.100:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by Ghostkeeper** [comment]
Yeah I think this is IT trying to phase out that computer even though we're still using it. Please refer to the Gitlab link for now. It's running the same tests.

**Comment by Ghostkeeper** [comment]
Actually, it turns out that this was because the hard disk of the hal9000 computer was full.

**Comment by digitalfrost** [comment]
I am not getting a Gitab link on #511 
Whereas there is one for #509
