### ISSUE TITLE
Scaling Mesh with Scene

### ISSUE THREAD

**Issue by CodyFagley** [Ultimaker/Uranium#544]
I am adding a mesh to a scene, where the mesh is exactly equivalent to a selected face on a model.  However, the model gets larger/smaller as the user zooms and the selected face stays the same.  

Is there a setting that I can set in my SceneNode or MeshData that forces the desired change?  See screenshots for more information.

Thanks!
![Screenshot from 2019-11-14 15-44-22](https://user-images.githubusercontent.com/11221762/68902492-b912e980-06f5-11ea-9d4f-bd329e36c9e9.png)
![Screenshot from 2019-11-14 15-44-28](https://user-images.githubusercontent.com/11221762/68902493-b912e980-06f5-11ea-8384-0225295f2977.png)
![Screenshot from 2019-11-14 15-44-32](https://user-images.githubusercontent.com/11221762/68902494-b912e980-06f5-11ea-9f2c-b79d1451c48c.png)

**Comment by nallath** [comment]
You're setting it as a part of the toolhandle. The default behavior of a toolhandle is to scale itself depending on the zoom of the camera (to ensure that it's rendered size is the same on screen).

You can disable this by setting the _auto_scale property to false in the constructor of the toolhandle.
