### ISSUE TITLE
noarch files but installed in arch dependand directory

### ISSUE THREAD

**Issue by arekm** [Ultimaker/Uranium#55]
I don't see any architecture dependant files in uranium (no binaries, only py files), yet python files get installed into /usr/lib/... where lib is for architecture dependant files.

python arch independant files should land in:
$ python3 -c "import sysconfig; print(sysconfig.get_path('purelib'))"
/usr/share/python3.4/site-packages

(so it should query python3 to know where to install files and not hardcode that path)

**Comment by awhiemstra** [comment]
You can set PYTHON_SITE_PACKAGES_DIR through CMake to determine where the files should go. By default it is $prefix/lib/python$pymajor.$pyminor/site-packages since at least my Arch system installs all python packages there.
