### ISSUE TITLE
SettingsView checkboxes disabled

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Uranium#56]
Currently checkboxes for certain options get disabled, depending on the values of other options.
E.g. when selecting AdhesionType skirt, all raft settings become grey in Preferences>Machine.

This is due to the fact that the "enable_if" field of fdmPrinter.json is used both for making settings disappear when not applicable as well as making these setting disabled in the settingsView.

The settingsView (Preferences>Machine) should disregard the "enable_if" field.

**Comment by fieldOfView** [comment]
This has not been an issue for a long time
