### ISSUE TITLE
No file/edit/view menu in Ubuntu Unity

### ISSUE THREAD

**Issue by Ghostkeeper** [Ultimaker/Uranium#61]
In applications produced with Uranium, the file/edit/view/etcetera menu is not displayed properly in Ubuntu Unity. The top bar appears to be empty, only displaying the name of the application (e.g. Cura). This makes a lot of functions inaccessible in Cura, such as the settings.

Other applications in Unity display the menu fine. @awhiemstra suspects that this issue is related to Qt5 and not up to Uranium to fix. Another application was found that runs on Qt5 that displayed the menu, but displayed it double (which may be unrelated, but may also be the result of an attempt to fix it).

Application version: 15.06.03
Platform: Ubuntu 15.04, with Unity
Qt version: I wouldn't know since the "About..." menu item is not accessible!

Steps to reproduce:
* Launch Cura.
* Move the cursor over the bar at the top of the screen.

Expected behaviour:
* The name "Cura" disappears.
* A menu appears with File, Edit, View, Help, and so on.

Observed behaviour:
* Nothing happens. No menu appears.

**Comment by nallath** [comment]
https://wiki.python.org/moin/PyQt/Getting%20the%20version%20numbers%20of%20Qt,%20SIP%20and%20PyQt

**Comment by Ghostkeeper** [comment]
All right, all right. The packages tell it to me as well. Both Qt and PyQt report version 5.4.1.

**Comment by Kepesk** [comment]
Confirmed.  Same versions of QT and PyQT.  Configuring unity to always show the menus or move the menus to the windows doesn't seem to help.

**Comment by nallath** [comment]
Ugh, this sounds like a 'This is bad and you should feel bad'. I can't imagine why unity developers thought this was a good idea :S

**Comment by Kepesk** [comment]
Workaround for Cura: start Cura from the command line with elevated privileges using

`sudo cura_app.py`

Then the menus appear in the window.

**Comment by nallath** [comment]
Yeah, but forcing the app to be launched in as super user is a bit weird imho.

**Comment by awhiemstra** [comment]
Any chance one of you can test one of the QtQuick examples like the QtQuick Controls Gallery example? I have a suspicion that those also fail, in which case it id an upstream bug.

**Comment by Ghostkeeper** [comment]
I confirm Kepesk's workaround. With elevated privileges the menu shows up, though not in the bar at the top of the screen but in the window itself, like is commonly done in Windows.

I have just installed RStudio, because [according to Wikipedia](https://en.wikipedia.org/wiki/Qt_%28software%29#Software_using_Qt), it uses Qt as well. There it always shows up with the menu in the window, Windows-style.

Perhaps the problem is that the data is wrongly passed to the window manager by Qt. If Cura is run as the root user, it has no access to the window manager (since the window manager is run by another user) and it falls back to displaying the menu in the window. But when Cura is run normally, it does have access to the window manager so it tries to send the data to the window manager and then fails for some reason, without having a fallback. I think RStudio fixed it by convincing Qt somehow to never use the window manager (on Unity).

**Comment by nallath** [comment]
Well, you can make a custom item that -looks- like the menu (and acts like it) but isn't quite the menu. I find that a pretty nasty work arround for something that should work (and does work for all other systems)

**Comment by Ghostkeeper** [comment]
I don't think that is desired, especially if it could cause the menu to show up double on some systems.

**Comment by Ghostkeeper** [comment]
@awhiemstra and I built an empty project with Qt Creator. While it had a defined menu, no menu was displayed in Unity.

@awhiemstra e-mailed me this link: https://bugs.launchpad.net/appmenu-qt5/+bug/1323853

It is a known bug, and out of our hands to fix.

**Comment by nickthetait** [comment]
In the interim there is no possible workaround? :'(

**Comment by Ghostkeeper** [comment]
You can get to the preferences by clicking on the select-a-printer dropdown, then clicking "Manage Printers".

**Comment by nickthetait** [comment]
Cool, thanks for the clarification.
