### ISSUE TITLE
A proper way to translate Cura plugins

### ISSUE THREAD

**Issue by Elkin-Vasily** [Ultimaker/Uranium#665]
I want to make MKS WiFi Plugin translatable. 

I have read Uranium/docs/translations.md. Looks like there is no right way to make custom .pot & .po files for plugin now.

The right way is to add additional translations to the cura.pot file?

**Comment by Elkin-Vasily** [comment]
I had figured out this by myself

**Comment by Ghostkeeper** [comment]
It's often considered polite to then share your findings with whoever is searching for the same problem in the future ;)

The intended solution here is to create your own i18n catalogue and add it to the `resources/i18n`. You can access the custom catalogue from a plug-in as well.
Although in the Settings Guide plug-in I've implemented translations simply by loading in different articles.

**Comment by Elkin-Vasily** [comment]
I want to write a wiki page about it and add here later.

**Comment by Elkin-Vasily** [comment]
[Here](https://github.com/Jeredian/mks-wifi-plugin/wiki/Cura-plugin-translation-guide) it is.
