### ISSUE TITLE
fcntl on Windows

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Uranium#69]
The new SaveFile class uses the "standard" fcntl to lock the file. This is not available on windows (resulting in an import error for the fcntl module). See https://www.safaribooksonline.com/library/view/python-cookbook/0596001673/ch04s25.html

**Comment by awhiemstra** [comment]
Yeah I know. I did a quick hack last friday to make the build work, but it should be fixed properly.

**Comment by fieldOfView** [comment]
Yep, that works!
