### ISSUE TITLE
SaveFile tries to overwrite a locked file

### ISSUE THREAD

**Issue by fieldOfView** [Ultimaker/Uranium#71]
The SaveFile class places a lock on the file that is to be written to before writing to a temp file. The temp file is then used to overwrite the original file, but this fails (at least on win32) because there is a lock on the original file.

Either the lock should be unlocked straight after succesfully making the lock (because we now know the file is writable), or before trying to replace the original file (instead of after)

See  https://github.com/Ultimaker/Cura/issues/412#issuecomment-142232427

**Comment by fieldOfView** [comment]
Moving ```self._file.close()``` to before ```os.replace(self._temp_file.name, self._path)``` fixes the issue for me on Windows, but I don't know if it doesn't introduce issues on other platforms.

**Comment by nallath** [comment]
I believe @awhiemstra already figured out the solution for this, but he hasn't implemented it yet.

**Comment by awhiemstra** [comment]
That was precisely the solution, but I do need to add a warning since unlocking the file before replacing it introduces a potential race condition where another process can lock the file just before the replace happens.

**Comment by awhiemstra** [comment]
This should now be fixed.
