### ISSUE TITLE
Add Printer form has unnecessary Ultimaker logos

### ISSUE THREAD

**Issue by LilBub** [Ultimaker/Uranium#72]
Marked in yellow

![image](https://cloud.githubusercontent.com/assets/14837299/10326515/1bf3d724-6c6a-11e5-8ef7-b0721f0abba3.png)

First, these are not needed.  Redundant.  The page already displays Ultimaker brand in "Type" and model name.

If you insist on using them (which is a bad idea), they need to be properly aligned to the form radio buttons.

**Comment by LilBub** [comment]
This belongs in the Cura section, not sure how to move this

**Comment by thopiekar** [comment]
@Ghostkeeper Good reason to allow issue report only on Cura and add additional tags for Uranium, Arcus and the *Engine.

@LilBub Totally agree. Still available in 2.1 branch and also guess master.

**Comment by nallath** [comment]
@fieldOfView @TMHogenhout What do you think about this? I agree that it's a bit overkill to mention ultimaker that often.

**Comment by fieldOfView** [comment]
I agree with @thopiekar and @LilBub. Not only is it overkill, but the layout is weird or broken (underscript?). I'll fix this when I'm going over this dialog.

**Comment by fieldOfView** [comment]
Fixed in 2.1 branch
