### ISSUE TITLE
ModuleNotFoundError: No module named 'pyArcus'

### ISSUE THREAD

**Issue by zhenhuashao** [Ultimaker/Uranium#805]
dock pull ultimaker:latest  images！
run cura-4.13.1 and   cranium-3.0.3 or cranium ！
提示ModuleNotFoundError: No module named 'pyArcus'！

**Comment by jellespijker** [comment]
arcus, savitar and pynest2d need to be recompiled with the new sip 6.5.0.
Male sure you install sip with pip
`python -m pip install sip` when you try to compile arcus, savitar and pynest2d you have to make sure that the site-packagea in which you installed sip can be found in the PYTHONPATH
