### ISSUE TITLE
Error loading conanfile when install Uranium

### ISSUE THREAD

**Issue by LowPower-Center** [Ultimaker/Uranium#872]
System: MacOS Ventura 13.2 python3.10

I install conan v1.59 ,  follow the develop device and when I run conan install instruction, I met this error:

 Error loading conanfile at 'xxx/GitHub/Uranium/conanfile.py': Version range '>=0.1.7' from requirement 'umbase/[>=0.1.7]@ultimaker/stable' required by 'py_require' could not be resolved in local cache

How can I fix this problem ?

<img width="697" alt="截屏2023-04-05 15 51 47" src="https://user-images.githubusercontent.com/69097122/230016784-c15c169d-5aa5-4cc9-96d1-c0d46ff59565.png">

**Comment by LowPower-Center** [comment]
I think this is becasue I remove cura from conan remote,now this work fine

**Comment by jellespijker** [comment]
also use conan 1.56.0
