### ISSUE TITLE
Environment Initialization problem

### ISSUE THREAD

**Issue by MaxSoloAT** [Ultimaker/Uranium#873]
Hello. I can't seem to install Uranium.
I set up conan everything is ok. The problem is in the following step. According to this [(https://github.com/Ultimaker/Uranium/wiki/Building-And-Developing)](url). When "conan install" I get _ERROR: Error loading conanfile at '/home/user/Uranium/conanfile.py': Version range '>=0.1.7' from requirement 'umbase/[>=0.1.7]@ultimaker/stable' required by 'py_require' could not be resolved in local cache_
Could you please tell me where I went wrong?
![inst1](https://user-images.githubusercontent.com/29458031/231667978-69c03fc1-1fa8-4666-b531-193e3e2b68ec.png)
![inst2](https://user-images.githubusercontent.com/29458031/231667980-8b068902-2fa0-4549-979d-b5daa3e65f54.png)

**Comment by jellespijker** [comment]
It looks like you're missing a Conan remote. Can you check the instructions on the Cura wiki https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source

**Comment by MaxSoloAT** [comment]
> It looks like you're missing a Conan remote. Can you check the instructions on the Cura wiki https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source

Yes you're right.
