### ISSUE TITLE
Is Storage Device Deprecated?

### ISSUE THREAD

**Issue by ad1217** [Ultimaker/Uranium#88]
It seems that the storage_device plugin type has been deprecated, but it is still mentioned in the plugin documentation. Are there plans to reintroduce it, or should these mentions be removed?

**Comment by nallath** [comment]
If I recall correctly these are deprecated. @awhiemstra can tell you for sure.

**Comment by Ghostkeeper** [comment]
They have been replaced with `output_device`.

**Comment by nallath** [comment]
So, any mention of those should be removed.

**Comment by fieldOfView** [comment]
This can be closed
